apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qy8p8wyh7-go 
  janus-idp.io/tekton: qy8p8wyh7-go
  backstage.io/kubernetes-id: qy8p8wyh7-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qy8p8wyh7-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  